# Generated by Django 5.0.6 on 2024-07-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_student_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="image",
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(),
        ),
    ]
