# Generated by Django 5.0.6 on 2024-07-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_student_image_alter_student_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(max_length=255),
        ),
    ]
