# Generated by Django 5.0.6 on 2024-07-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_student_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=15)),
                ("speed", models.IntegerField()),
                ("Cost", models.IntegerField(verbose_name=models.IntegerField())),
            ],
        ),
        migrations.DeleteModel(
            name="Products",
        ),
    ]
