# Generated by Django 5.0.6 on 2024-07-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_car_delete_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="Cost",
            field=models.IntegerField(),
        ),
    ]
