# Generated by Django 5.0.6 on 2024-07-22 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recepe", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
