# Generated by Django 5.0.6 on 2024-07-27 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recepe", "0005_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
