# Generated by Django 5.0.6 on 2024-07-31 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recepe", "0006_delete_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRecord",
        ),
    ]
