# Generated by Django 5.0.6 on 2024-08-01 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recepe", "0008_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
