# Generated by Django 5.0.6 on 2024-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recepe", "0010_userinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformation",
            name="Picture",
            field=models.ImageField(blank=True, null=True, upload_to="Image"),
        ),
    ]
