# Generated by Django 5.0.6 on 2024-10-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recepe", "0012_remove_userinformation_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformation",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
